name: gcov2lcov-action

description: "convert golang coverage to lcov format"

inputs:
  infile:
    description: "go coverage input file"
    required: true
    default: coverage.out
  outfile:
    description: "lcov output file"
    required: true
    default: coverage.lcov
  version:
    description: "gcov2lcov version"
    required: true
    default: latest
  working-directory:
    description: "change working directory"
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      working-directory: ${{ inputs.working-directory }}
      env:
        INFILE: ${{ inputs.infile }}
        OUTFILE: ${{ inputs.outfile }}
        VERSION: ${{ inputs.version }}
