name: gcov2lcov-action

description: "convert golang coverage to lcov format"

inputs:
  infile:
    description: "go coverage input file"
    required: false
    default: coverage.out
  outfile:
    description: "lcov output file"
    required: false
    default: coverage.lcov
  version:
    description: "gcov2lcov version"
    required: false
    default: latest
  working-directory:
    description: "change working directory"
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: 'set -x && curl -sLf "${RELEASE}/${NAME}.tar.gz" | tar zxf - --strip 1'
      working-directory: /tmp
      env:
        NAME: "gcov2lcov-linux-amd64"
        RELEASE: "https://github.com/jandelgado/gcov2lcov/releases/${{inputs.version}}/download"
    - shell: bash
      run: set -x && /tmp/gcov2lcov-linux-amd64 -infile "${{ inputs.infile }}" -outfile "${{ inputs.outfile }}"
      working-directory: ${{ inputs.working-directory }}
