name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare
        run: git init
        working-directory: testdata
      - name: Run gcov2lcov-action
        uses: ./
        with:
          working-directory: testdata
      - name: Diff
        run: diff -y coverage_expected.lcov coverage.lcov
        working-directory: testdata
